Feature 1516 use case mvmode
dtcenter/METplus pull request #2094
Opened 2023-03-17 16:34 UTC by hertneky

This satisfies issue #1516. This adds a new use-case demonstrates running multivariate MODE to identify complex blizzard-like objects. The use-case runs multivariate MODE with categorical snow, visibility, and 10-m winds as inputs to generate forecast and observed 'super' objects. It then runs MODE traditionally to compare the 'super' objects for wind intensities.

The use case makes use of previous enhancements to the MODE wrapper to support multivariate MODE, including:
- Addition of multivar_logic config option
- Support of files lists for multiple input files

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

Use case tested on RAL machine by myself and @j-opatz . Documentation was reviewed.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Use case already tested.
Documentation can be reviewed [here](https://metplus.readthedocs.io/en/feature_1516_usecase_mvmode/)
Review automated tests

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [ ] Do these changes include sufficient testing updates? **[Yes]**

- [ ] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

New output from new multivariate MODE use-case

- [ ] Please complete this pull request review by **[Aril 7th]**.</br>

For beta2 release

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-04-05 19:34 UTC, j-opatz commented on docs/use_cases/model_applications/short_range/MODEMultivar_fcstHRRR_obsMRMS_HRRRanl.py
> +#        run_metplus.py -c /path/to/METplus/parm/use_cases/model_applications/short_range/MODEMultivar_fcstHRRR_obsMRMS_HRRRanl.conf -c /path/to/user_system.conf
The documentation for this is slightly outdated. A user no longer needs the "-c" between each configuration file. These should be removed here, as well as the second method of running the use case (just below this line).

2023-04-05 19:35 UTC, j-opatz requested changes
Documentation has one minor fix that was noted. Otherwise, use case once again was proven to run successfully, and all of the automated tests came back successful outside of the new content created from this use case. Please fix the documentation and re-request my review and I'll approve.

2023-04-05 22:38 UTC, georgemccabe commented
@j-opatz , @hertneky , we have needed to reconcile the use case documentation files to be consistent (issue #681) for a while but have not had the funding to do so. I can do a quick pass through this doc file and clean it up. I'll push my changes to this branch and reply here when I do that.

2023-04-05 23:09 UTC, georgemccabe commented
@j-opatz, I made the updates to the use case doc file. It should take a few minutes to rebuild, but you can view it here:
https://metplus.readthedocs.io/en/feature_1516_usecase_mvmode/generated/model_applications/short_range/MODEMultivar_fcstHRRR_obsMRMS_HRRRanl.html#running-metplus

2023-04-06 01:28 UTC, j-opatz approved these changes
The updated documentation addressed the previous concern and is now approved

2023-04-06 15:53 UTC, merged

2023-04-06 18:17 UTC, hertneky commented
@georgemccabe @j-opatz Thanks for the help with this!