Feature #2282 coord_release_docs
dtcenter/METplus pull request #2288
Opened 2023-08-02 22:50 UTC by JohnHalleyGotway

## Pull Request Testing ##

Big picture, I defined what a "coordinated release" means and created instructions for creating a new one. This enabled me to remove a couple of the instructions from the component release instructions. I *think* these changes are in pretty good shape but will rely heavily on your review for completeness and edits.

- [x] Describe testing already performed for these changes:</br>
Rendered and reviewed docs locally to confirm they works as expected.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please review the proposed changes at:

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**
That's all it is.

- [x] Do these changes include sufficient testing updates? **[Yes]**
None needed.

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[Monday 8/7/23]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] fter submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-08-03 12:55 UTC, georgemccabe commented on docs/Contributors_Guide/github_workflow.rst
Line 66 should change from:

> (e.g. **METplus-5.1.0 Development**)

to

> (e.g. **METplus-Wrappers-5.1.0 Development**)

2023-08-03 13:01 UTC, georgemccabe commented on docs/Release_Guide/index.rst
> +An official release is a stable release of a METplus component and is basically
```suggestion
An official release is a stable release of a METplus component and typically matches
```

2023-08-03 13:05 UTC, georgemccabe commented on docs/Release_Guide/index.rst
>  #. **Official Release** (e.g. vX.Y.Z) from the develop branch (becomes the new main_vX.Y branch)
```suggestion
#. **Official Release** (e.g. vX.Y.0) from the develop branch (becomes the new main_vX.Y branch)
```

2023-08-03 13:07 UTC, georgemccabe commented on docs/Release_Guide/coordinated.rst
> +bugfix component releases have already been created. Note however that
```suggestion
bugfix component releases have already been created. Note, however, that
```

2023-08-03 13:23 UTC, georgemccabe requested changes
These changes look good overall. I like that there are dedicated instructions for creating a coordinated release and steps that were previously found in the release guide for each component are now in a dedicated section so that there is no confusion as to who should complete these tasks.

I made a few minor suggestions that are not required. Feel free to accept or deny them as you feel appropriate.

2023-08-03 15:58 UTC, georgemccabe approved these changes
I approve. Thanks for making those edits.

2023-08-03 16:17 UTC, lisagoodrich commented
Hi @georgemccabe,
I need a little more guidance.  I couldn't find the word "Save" anywhere on the page that you linked to.
I completely agree that "Save" should be bolded.  @jprestop, we don't define this in the User's Guide.  I think we should.  What do you think?
========
@lisagoodrich, please advise on proposed formatting changes. I changed...
From Italics: "Click the Save button"
To Bold: "Click the Save button"
Per https://github.com/dtcenter/METplus/issues/1667, I'm not sure which it should be. My personal opinion is that bold sticks out better than italics, but please LMK what standard you've already defined, if any.
=========
Since I couldn't find the word "Save" on the main page, I started poking around and found this:
https://metplus--2288.org.readthedocs.build/en/2288/Release_Guide/metplus_official.html#create-release-on-github
The directories listed should be in italics.  I'm not sure if this is within the scope of this pull request or not.  If you point me to the correct page, I'm happy to check formatting.

2023-08-03 16:17 UTC, JohnHalleyGotway commented on docs/Contributors_Guide/github_workflow.rst
Just updated that. Thanks for finding it.

2023-08-03 19:11 UTC, JohnHalleyGotway commented
@lisagoodrich, I'm moving comments over from Slack to a comment on this discussion:

Let me point out the diffs more clearly...

Please compare the formatting:
- In this existing version: https://metplus.readthedocs.io/en/latest/Release_Guide/metplus_official.html#update-dtc-website
- To my pull request version: https://metplus--2288.org.readthedocs.build/en/2288/Release_Guide/metplus_official.html#update-release-notes

The difference is in italics vs bold.

So for anything that's the name of an "entry" on the release page to be filled out, I used bold. And then I enclosed the value in parentheses. For example:
 - Select the **Release Type** (“Recommended” for official or bugfix releases or “Development” for development versions).

And my question is whether or not we've defined the use of italics vs bold vs parentheses for this sort of thing?

2023-08-03 19:19 UTC, jprestop commented
>  @jprestop, we don't define this in the User's Guide. I think we should. What do you think?

@lisagoodrich We can definitely talk about adding this sort of information to the Contributor's Guide for bolding.

> Since I couldn't find the word "Save" on the main page, I started poking around and found this:
https://metplus--2288.org.readthedocs.build/en/2288/Release_Guide/metplus_official.html#create-release-on-github
The directories listed should be in italics.

With regard to the above quote @lisagoodrich what directories are you referring to that should be in italics?  Can you please give an example or two so I can find the correct place?

@JohnHalleyGotway I'm going to add a few suggestions on individual lines and will follow up momentarily.

2023-08-03 19:38 UTC, jprestop commented
@JohnHalleyGotway Actually, after reviewing, I don't have any suggestions.  I do see some funky formatting with "https://" in this section: https://metplus--2288.org.readthedocs.build/en/2288/Release_Guide/metplus_bugfix.html#create-release-on-github but I don't think you changed anything on that page...

2023-08-03 20:04 UTC, lisagoodrich commented
@jprestop, my mistake.  I was skimming and thought the web addresses were directories.  Please ignore.

@JohnHalleyGotway, the formatting looks fine to me.  It looks the same in both versions.  I'm assuming that is what you want.  I only looked at this on the web pages.  Is there somewhere I should be reviewing this in Github?  I'm not sure what to do.
The only feedback I have is, in the User's Guide, we are not using second person (you).  We're keeping it in third person, (the contributor, the user etc.) But I don't know what we'd want to do the same for the Contributor's guide.

2023-08-03 20:24 UTC, jprestop approved these changes

2023-08-03 20:29 UTC, lisagoodrich commented
@JohnHalleyGotway, I'm sorry I haven't reviewed anything this big before.  Do I click "Squash and merge" or will this mess things up?

2023-08-03 20:33 UTC, jprestop commented
> @JohnHalleyGotway, I'm sorry I haven't reviewed anything this big before. Do I click "Squash and merge" or will this mess things up?

@lisagoodrich Thanks for checking in.  There are still some things here that @JohnHalleyGotway may wish to respond to.  You should not click "Squash and merge".   According to our [Merging Pull Requests](https://metplus.readthedocs.io/en/develop/Contributors_Guide/github_workflow.html#merging-pull-requests) section of the Contributor's Guide: "**As permissions allow, the requestor is responsible for merging the pull request once it has been approved.**" so John should be the one to "Squash and merge".  :)

2023-08-07 20:17 UTC, JohnHalleyGotway commented
@lisagoodrich should I be waiting for your approval on this PR? Is this something you're planning to do? Or should I remove you as a reviewer and proceed with the feedback from Julie and George?

2023-08-07 21:15 UTC, lisagoodrich commented
@JohnHalleyGotway, @jprestop told me I didn't need to approve it.  So I didn't.  She said only one person needs to approve it and that's normally what you prefer.  If you like, I can find my directions on how to do this and approve it or you can just remove me.

2023-08-07 21:27 UTC, merged