Feature 1488 usecase satwinds
dtcenter/METplus pull request #2324
Opened 2023-08-29 00:58 UTC by j-opatz

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>Ran on Seneca, confirmed that ice cover conda env works. Data was pushed up to Mohawk and marine and cryo tarball was updated. 

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>Review documentation here: https://metplus.readthedocs.io/en/feature_1488_usecase_satwinds/generated/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.html#sphx-glr-generated-model-applications-marine-and-cryosphere-pointstat-fcstgfs-obsascat-satellitewinds-py</br>if desired, check that use case runs for personal test. Data is on Seneca, under /d1/personal/jopatz/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [ ] Do these changes include sufficient testing updates? **[Yes]**

- [ ] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>New truth data for use cases

- [ ] Please complete this pull request review by **[Fill in date]**.</br>09/11/23

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-08-30 22:01 UTC, georgemccabe requested changes
I made a few suggested edits, but everything looks good otherwise. I confirmed the use case ran successfully and generated new data.

2023-08-30 22:01 UTC, georgemccabe commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +# https://metplus.readthedocs.io/en/latest/generated/met_tool_wrapper/PointStat/PointStat.html
```suggestion
# https://metplus.readthedocs.io/en/latest/generated/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.html
```

2023-08-30 22:01 UTC, georgemccabe commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +CONFIG_DIR = {PARM_BASE}/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds
I recommend moving `CONFIG_DIR` above so it comes directly before its use in `OBS_POINT_STAT_INPUT_TEMPLATE`

2023-08-30 22:01 UTC, georgemccabe commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +POINT_STAT_CONFIG_FILE ={PARM_BASE}/met_config/PointStatConfig_wrapped
You could remove this variable since it is using the default. This is optional

2023-08-30 22:01 UTC, georgemccabe commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +POINT_STAT_MET_CONFIG_OVERRIDES = land_mask = { flag = TRUE;}
It would be good to support setting the land_mask variables instead of using overrides. If an issue does not already exist, we should create one.

2023-08-30 22:01 UTC, georgemccabe commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds/read_ASCAT_data.py
> +    sys.exit()
You don't need to run `sys.exit()` because the same behavior will occur when the end of the script is hit.
However, it would be cleaner to instead check if the arguments split by `:` is not equal to 5, then log the command and exit 1 (0 return code indicates success, while non-zero indicates a failure). That would let you remove the indent on all of the code inside the if block. Let me know if you'd prefer I make this change.

From line 21:
```
if len(sys.argv[1].split(':')) != 5:
    print("Run Command:\n\n read_ascat_data.py /path/to/input/input_files:start_date:end_date:Message_type:Variable\n\nCommands notes:\n-start and end dates are formatted YYYYMMDDHHMMSS\n-Suggested Message_types are WDSATR or SATWND, refer to MET User's Guide for more info\n")
    sys.exit(1)

try:
    input_dir,st_date,en_date,msg_typ,var_typ = sys.argv[1].split(':')

...

```

2023-08-30 22:01 UTC, georgemccabe commented on docs/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.py
> +# with the -c option, i.e. -c parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
```suggestion
# parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
```
-c option is no longer required

2023-08-31 16:45 UTC, j-opatz commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds/read_ASCAT_data.py
> +    sys.exit()
As requested, try was redone to allow for indentation fix

2023-08-31 16:46 UTC, j-opatz commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +POINT_STAT_CONFIG_FILE ={PARM_BASE}/met_config/PointStatConfig_wrapped
Variable removed

2023-08-31 16:46 UTC, j-opatz commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +CONFIG_DIR = {PARM_BASE}/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds
CONFIG_DIR relocated

2023-08-31 20:56 UTC, j-opatz commented on parm/use_cases/model_applications/marine_and_cryosphere/PointStat_fcstGFS_obsASCAT_satelliteWinds.conf
> +POINT_STAT_MET_CONFIG_OVERRIDES = land_mask = { flag = TRUE;}
Issue was created, not assigned to a cycle yet

2023-09-13 21:04 UTC, merged