Feature 2253 tc csv writer
dtcenter/METplus pull request #2373
Opened 2023-09-28 06:07 UTC by John-Sharples

Note this is a DRAFT pull request. It's build on top of existing PR https://github.com/dtcenter/METplus/pull/2369 and shouldn't be merged until that PR is resolved.

Two changes:
- 29e2d47e383839289c9548fdfc151afe3011534b This change adds tests for the existing function `read_modify_write_file` and adds a comment about a potential bug. Not being familiar with the input data I don't know if this bug will ever be present in real data.

- 7d149ee33d825ad05bf1fe730469d177e98650dc and 795b94fdada95522020f1403dc3987ac5fc05d27 which changes source code, not just tests. This is a proposed alternative implementation of `read_modify_write_file` using pandas. It attempts to exactly mimic existing behaviour, but avoids the bug mentioned above.  You may not want to adopt this as it introduces `pandas` as a dependency. Further simplifications can be made if the existing behaviour doesn't need to be preserved, e.g. whitespace after delimiting commas.

If the second change is not wanted, I will close and reopen with only the tests for the existing function.

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: @georgemccabe 
Select: METplus-Wrappers-6.0.0 Development
Select: METplus-6.0.0
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-09-28 18:02 UTC, georgemccabe requested changes
The input files that would be passed to the wrapper with the reformat SBU option have a very specific format. The 3rd column contains a long string that would not be found elsewhere in the file, e.g. 2014121312_F000_611S_0268W_FOF. However, I agree that the logic doesn't match the comment that it is deleting the 3rd column only. We would prefer to avoid adding a dependency on pandas, even though it does look like a good, clean solution. I suggest we use enumerate to get the index of the column to ensure that only the 3rd column is skipped:

```
for index, item in enumerate(row):
    if index == 2:
        continue
```

2023-10-01 21:58 UTC, John-Sharples commented
Thanks for the feedback, @georgemccabe. I'll make your suggested changes and resubmit with just the tests.

2023-10-02 03:07 UTC, John-Sharples commented
Updated as per discussion. Also added a new test to cover error message in `_get_basin_cyclone_from_bdeck`

2023-10-02 21:00 UTC, georgemccabe approved these changes

2023-10-02 21:01 UTC, merged