Feature 2388 update tci
dtcenter/METplus pull request #2550
Opened 2024-04-11 15:01 UTC by DanielAdriaansen

Closes #2388. 

Includes:
1. New table of contents at top of use case docs file
2. Updated FCST python embedding script
3. Updated OBS Python embedding script
4. New station metadata file required for the OBS data
5. Reorganized and updated use case conf file
6. New OBS sample data
 
- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/overview.html#metplus-components-python-requirements) table.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2024-04-15 22:26 UTC, georgemccabe commented
@DanielAdriaansen, could you fill out the pull request template? It would be useful to know what testing is expected of the reviewers and if the differences in the use case output are expected.

2024-04-16 14:52 UTC, DanielAdriaansen commented
> @DanielAdriaansen, could you fill out the pull request template? It would be useful to know what testing is expected of the reviewers and if the differences in the use case output are expected.

Done, sorry about that. I had this in draft and converted it as ready but forgot to go back and add the details.

2024-04-16 15:16 UTC, georgemccabe commented
[Documentation changes](https://metplus--2550.org.readthedocs.build/en/2550/generated/model_applications/land_surface/PointStat_fcstCESM_obsFLUXNET2015_TCI.html#sphx-glr-generated-model-applications-land-surface-pointstat-fcstcesm-obsfluxnet2015-tci-py) from this PR

2024-04-16 15:24 UTC, DanielAdriaansen commented
Looking closer at the difference tests from CI, I note that there were unexpected differences in the FCST data. However, way back I fixed a bug here: https://github.com/dtcenter/METplus/issues/2388#issuecomment-1787789180, and the differences were only in MAM and JJA so that is reassuring and DJF and SON show zero differences. Thus, the formulation of TCI remains the same, and is being called correctly for the FCST.

I spot checked a few OBS sites. From the `point_stat` MPR files for DJF, I see:

Truth:
Borgo Cioffi                                                              40.52375   14.95744      10       0   4.62984    0.42177
Tonzi Ranch                                                              38.4316  -120.96598      10       0  -2.23139    1.7888
Grignon                                                              48.84422    1.95191      10       0  -1.09105    1.2232

Output:
IT-BCi    40.5237   14.9574       10       0   4.62984    0.95305
US-Ton    38.4309 -120.966        10       0  -2.23139    2.91969
FR-Gri    48.8442    1.9519       10       0  -1.09105    0.717

What we can see is that:
1) FCST values match
2) OBS values do not match, but the sign is the same and the new values are higher for these three sites
3) The station metadata (lat/lon) matches

The OBS values being different here is almost certainly driven by differences in decisions about what quality of raw FLUXNET data to include in the TCI calculation, compared to whatever data the previous TCI provider chose to use. I'm not sure there's a way to quantify this, but rather just be confident in our data filtering and take the matching FCST values as an indicator the actual math for computing TCI remains unchanged.

2024-04-16 15:53 UTC, georgemccabe requested changes

2024-04-16 15:53 UTC, georgemccabe commented on docs/use_cases/model_applications/land_surface/PointStat_fcstCESM_obsFLUXNET2015_TCI.py
>  # | **Location:** All of the input data required for this use case can be found in the met_test sample data tarball. Click here to the METplus releases page and download sample data for the appropria
```suggestion
# | **Location:** All of the input data required for this use case can be found in the land_surface sample data tarball. Click here to the METplus releases page and download sample data for the appropriate release: https://github.com/dtcenter/METplus/releases
```

2024-04-16 17:03 UTC, georgemccabe approved these changes
I added the new data for the v6.0 and develop branches, then confirmed that I could run the use case on seneca using the new data.

I approve, pending @anewman89's review

2024-04-17 17:32 UTC, anewman89 commented
@DanielAdriaansen Thanks for the testing and explanation of the results.  I agree it seems like we're ok with the TCI computation. I also approve the PR.

2024-04-17 17:32 UTC, anewman89 approved these changes

2024-04-17 19:12 UTC, merged