Feature 2743 nrl gfs cloud analysis
dtcenter/METplus pull request #2850
Opened 2024-12-24 01:39 UTC by CPKalb

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Ran the use case and tested to be sure it works as expected

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Run the use case to verify that it runs and produces the expected output (clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.conf).  Review the documentation for any errors and inconsistencies.
Steps to run the use case:
1.  The data is located on seneca in the following directories:
/d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/GFS_0.25
/d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/analysis
/d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/masks
2.  Check out the feature_2743_nrl_gfs_cloud_analysis branch of METplus
3. Minna's mp_analysis_env conda environment on seneca has all the necessary packages:/d1/personal/mwin/miniconda3/envs
4. Check out the develop branch of METcalcpy, METplotpy, and METdataio.  These branches need to be in your Python path or conda environment.  Currently, the Python path is set in the use case for these repositories to be in the same directory as the METplus repository.  If the locations are different, this will need to be changed in the [user_env_vars] section of the .conf file
5. Run the use case and verify that the output matches the output in the following directories on seneca:
Mask: /d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/masks/West_Pacific.nc

Grid-Stat: /d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/grid_stat

MODE: /d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/mode

Stat-Analysis: /d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/stat_analysis

Reformatted data: /d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/reformatted/reformat_CTS.data

Plots: /d1/personal/kalb/NRL/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/plots

The use case will take a while to run (an hour for me on seneca).  It runs in 18 mins on GitHub actions due to ci overrides.

The documentation for review is here: https://metplus.readthedocs.io/en/feature_2743_nrl_gfs_cloud_analysis/generated/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.html#sphx-glr-generated-model-applications-clouds-gridstat-fcstgfs-obsgfs-cloudfraclayer-py

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**
Yes

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**
Yes

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:
No

- [ ] Please complete this pull request review by **[Fill in date]**.</br>
Dec 30?

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Add any new Python packages to the [METplus Components Python Requirements](https://metplus.readthedocs.io/en/develop/Users_Guide/appendixA.html#metplus-components-python-packages) table.
- [ ] For any new datasets, an entry to the [METplus Verification Datasets Guide](https://metplus.readthedocs.io/en/latest/Verification_Datasets/index.html).
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **METplus-Wrappers-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2025-03-24 15:30 UTC, DanielAdriaansen requested changes
I made some minor suggested changes to the documentation. Have a look, and once you decide which if any you'd like to accept, I'll go ahead and add my approval and we can get this merged in. I sent an email with some additional questions as well so maybe we'll chat about those first too. Thanks @CPKalb!

2025-03-24 15:30 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# Additionally, plots are created to demonstrate how to reformat and visualize GSS
```suggestion
# Additionally, plots are created to demonstrate how to reformat and visualize GSS,
```

2025-03-24 15:30 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# CSI and frequency bias from the command line.
```suggestion
# CSI, and frequency bias from the command line.
```

2025-03-24 15:30 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# This use case calls GenVxMask once, GridStat once, MODE three times, StatAnalysis
Do you say "GridStat once" here to reflect GHA? I think if the user runs it MODE and GridStat both run the same number of times, is that correct? If so we may want to just say that here rather than write about what GHA does.

2025-03-24 15:30 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# three lead times for each for a total of 3 valid times, listed below.
```suggestion
# three lead times for a total of 3 valid times, listed below.
```

2025-03-24 15:30 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# There are two python scripts used in this use case.  The first is
```suggestion
# There are two Python UserScripts used in this use case.  The first is 
```

2025-03-24 15:57 UTC, j-opatz commented on .github/parm/use_case_groups.json
> +    "index_list": "6",
Let's update this to 8 to avoid the other two use cases (6 and 7) that have already gone in ahead of this one.

2025-03-24 20:02 UTC, CPKalb commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# This use case calls GenVxMask once, GridStat once, MODE three times, StatAnalysis
It's more "GridStat once" to reflect the number of times it's called in the process list.

2025-03-24 20:38 UTC, CPKalb commented on .github/parm/use_case_groups.json
> +    "index_list": "6",
This should now be done

2025-03-25 14:59 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# This use case calls GenVxMask once, GridStat once, MODE three times, StatAnalysis
OK gotcha- maybe an easy follow-up question then. How come MODE has three sections for low/mid/high cloud but GridStat doesn't need that? What specific to MODE is happening for each of those variables that can't be controlled via MODE_FCST_VAR<n>_NAME, etc.? Is it just `MODE_OUTPUT_PREFIX` that's changing?

2025-03-25 15:00 UTC, DanielAdriaansen commented on .github/parm/use_case_groups.json
> +    "index_list": "6",
Thanks @CPKalb !

2025-03-25 15:46 UTC, DanielAdriaansen commented
@CPKalb I see that the Python UserScripts have two code smells and the `reformat_CTS_linetype.py` has more than 3% duplicated code (5%) so it is flagged. Are you able to resolve these or do we need to loop someone else in?

2025-03-25 16:12 UTC, CPKalb commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# This use case calls GenVxMask once, GridStat once, MODE three times, StatAnalysis
Grid-Stat can take different variables and thresholds for those variables in the same run.  However, if you give MODE multiple variables, it asks for multivariate logic and tries to run Multivariate MODE.  So, to run MODE individually on each variable, you need 3 runs of MODE.  But, for Grid-Stat, you can get statistics for each variable in the same run so only one is needed.

2025-03-25 16:14 UTC, CPKalb commented
reformat_CTS_linetype.py should have more than 5% duplicated code (it's mostly duplicated code).  But, I am unsure the best way to resolve it.

2025-03-25 16:47 UTC, DanielAdriaansen commented
> @DanielAdriaansen reformat_CTS_linetype.py should have more than 5% duplicated code (it's mostly duplicated code). But, I am unsure the best way to resolve it.

This is related to our email conversation with @georgemccabe about a central place to keep this, right? George, can we just ignore this SonarQube finding? I think the other one about the generic `Exception` and the unused local variable can probably be handled- Tina can you do that or want me to take a look?

2025-03-25 16:48 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# This use case calls GenVxMask once, GridStat once, MODE three times, StatAnalysis
OK great! I may add some minor wording to the documentation to this effect for clarity, this makes perfect sense but wasn't immediately obvious to me. Thanks!

2025-03-25 16:55 UTC, DanielAdriaansen commented on docs/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer.py
> +# This use case calls GenVxMask once, GridStat once, MODE three times, StatAnalysis
Changes are in 992a6924cfe4cf701c0a96ae58ee9a8908779890

2025-03-25 17:07 UTC, georgemccabe commented on .github/parm/use_case_groups.json
> -    "category": "clouds",
You'll need to add this back!

2025-03-25 17:07 UTC, georgemccabe commented on .github/parm/use_case_groups.json
> +    "run": true
and turn this to false

2025-03-25 17:08 UTC, georgemccabe commented on .github/parm/use_case_groups.json
> +    "run": true
```suggestion
    "run": false
```

2025-03-25 17:15 UTC, georgemccabe commented
@DanielAdriaansen, if I recall correctly, I wanted to create a wrapper to handle this common scripting for calling METplus Analysis tools (issue #2851), but we don't have funding for this work at this time. I think you could either:
1) Create a directory called `common` or something similar under the `parm/use_cases/model_applications/clouds` directory to put the script that is a duplicate and update the use cases that use it to call it from that path

OR for the sake of time

2) Ignore the duplicate complaint and we will address this at another time

2025-03-25 17:18 UTC, CPKalb commented on .github/parm/use_case_groups.json
> +    "run": true
I'm confused here.  This is the new use case, so we want to run the tests on it.  Wouldn't setting it to false turn them off?

2025-03-25 17:26 UTC, CPKalb commented on .github/parm/use_case_groups.json
> -    "category": "clouds",
I added this back where it was missing

2025-03-25 17:42 UTC, georgemccabe commented on .github/parm/use_case_groups.json
> +    "run": true
This controls if the use case group is run for push events. For a pull request and develop/main branches, all use cases are run regardless of this value. We want to turn a new use case to `run: false` before merging it, otherwise all branches created off of develop will run this use case for every push event.

2025-03-25 17:50 UTC, CPKalb commented on .github/parm/use_case_groups.json
> +    "run": true
Ah, I remember this now. Thanks.  I will fix this

2025-03-25 17:57 UTC, CPKalb commented
@DanielAdriaansen and @georgemccabe, I made modifications to handle the Exception and unused variable that were in the SonarCube findings.  However, it seems SonarCube is working now.  I don't know what happened to the duplicate code SonarCube finding since I didn't make any changes to address it.  Perhaps the changes with the Exception and unused variable made the code different enough that it's no  longer a problem?

2025-03-25 18:47 UTC, CPKalb commented
Does anyone know why we are getting failures in the met_tool_wrapper use cases and the tc_and_extra_tc?  No changes were made to any of those use cases in this branch

2025-03-25 18:51 UTC, DanielAdriaansen commented
> Does anyone know why we are getting failures in the met_tool_wrapper use cases and the tc_and_extra_tc? No changes were made to any of those use cases in this branch

Maybe something inherited from `develop` after merging? Any thoughts @georgemccabe?

2025-03-25 18:51 UTC, georgemccabe commented
@CPKalb , the develop-ref was supposed to be updated, but it looks like [that run](https://github.com/dtcenter/METplus/actions/runs/14046376710) failed because the clouds:7 use case failed in develop. Perhaps the data needed for that use case was not added to main_v6.1 on mohawk?

2025-03-25 18:52 UTC, DanielAdriaansen commented
> @CPKalb , the develop-ref was supposed to be updated, but it looks like [that run](https://github.com/dtcenter/METplus/actions/runs/14046376710) failed because the clouds:7 use case failed in develop. Perhaps the data needed for that use case was not added to main_v6.1 on mohawk?

I think @j-opatz was doing the data updating, but he was waiting for this use case to do them both together.

Is that right John O?

2025-03-25 19:18 UTC, j-opatz commented
> > @CPKalb , the develop-ref was supposed to be updated, but it looks like [that run](https://github.com/dtcenter/METplus/actions/runs/14046376710) failed because the clouds:7 use case failed in develop. Perhaps the data needed for that use case was not added to main_v6.1 on mohawk?
> 
> I think @j-opatz was doing the data updating, but he was waiting for this use case to do them both together.
> 
> Is that right John O?

That's correct; I was awaiting both use cases to be in the repo before updating the truth data branch. I have been keeping up with getting the test data into mohawk, though.

I thought @georgemccabe mentioned yesterday afternoon that an update in MET necessitated an update to the truth data anyways? So this may not be the source of the issue.

2025-03-25 19:54 UTC, georgemccabe commented
It looks like the error is in the python embedding script:

> KeyError: "No variable named 'pres'. Did you mean one of ('avg_pres',)?"

Was this tested using Python 3.12.0? Perhaps that is the source of the failure?

2025-03-25 20:37 UTC, CPKalb commented
The use case I added doesn't use python embedding so I'm unclear what script this error is coming from....

2025-03-25 21:09 UTC, CPKalb commented
It looks like the met_tool_wrapper failures are mostly differences.  Although I don't know why

2025-03-25 21:26 UTC, georgemccabe commented
@CPKalb, I saw it was an error in a python script, so I assumed python embedding. The met_tool_wrapper and tc diffs are from MET changes that were supposed to be updated in the truth data, but the `develop-ref` run to update the truth couldn't complete due to the use case failure.

2025-03-25 22:06 UTC, DanielAdriaansen approved these changes, later dismissed
Thanks a ton for the documentation feedback, report input, and fixing those SonarQube findings @CPKalb! This use case will be a great addition for NRL. I approve.

2025-03-25 23:27 UTC, CPKalb commented
Great.  @georgemccabe, am I okay to merge this despite the failures in the met_tool_wrappers?

2025-03-26 13:42 UTC, georgemccabe commented
It looks like the use case from this PR is failing in the tests. You'll need to fix that before it can be merged.

https://github.com/dtcenter/METplus/actions/runs/14067774540/job/39394680572?pr=2850

> COMMAND:
> /metplus/METplus/metplus/parm/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/reformat_CTS_linetype.py
> 
> OUTPUT:
> {'line_type_load': False, 'load_stat': True, 'load_mode': True, 'load_mtd': True, 'load_mpr': False, 'load_orank': False, 'force_dup_file': False, 'verbose': False, 'stat_header_db_check': True, 'tcst_header_db_check': True, 'mode_header_db_check': True, 'mtd_header_db_check': True, 'drop_indexes': False, 'apply_indexes': False, 'load_xml': True}
> []
> Traceback (most recent call last):
>   File "/metplus/METplus/metplus/parm/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/reformat_CTS_linetype.py", line 60, in <module>
>     main()
>   File "/metplus/METplus/metplus/parm/use_cases/model_applications/clouds/GridStat_fcstGFS_obsGFS_cloudFracLayer/reformat_CTS_linetype.py", line 42, in main
>     logger.info("Time to read input .stat data files using METdbLoad: "+time_to_read)
>                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
> TypeError: can only concatenate str (not "float") to str

2025-03-26 16:58 UTC, georgemccabe approved these changes

2025-03-26 16:58 UTC, merged