Feature 437 tc rmw
dtcenter/METplus pull request #499
Opened 2020-06-04 19:46 UTC by georgemccabe

A new wrapper (TCRMW) and 3 new use cases are found in this PR. I also added new tests for config and the new wrapper. The new cases can be run on kiowa.

2020-06-19 19:00 UTC, JohnHalleyGotway commented on docs/Users_Guide/wrappers.rst
> +| :term:`TC_RMW_STORM_ID`
Shouldn't we have an entry here for "TC_RMW_MODEL"?

2020-06-19 19:02 UTC, JohnHalleyGotway commented on docs/Users_Guide/wrappers.rst
> +
Should also have an entry for TC_RMW_LEAD_LIST.

2020-06-19 19:03 UTC, JohnHalleyGotway commented on docs/Users_Guide/wrappers.rst
> +
Add entry for model here.

2020-06-19 19:06 UTC, JohnHalleyGotway requested changes
Please make minor updates to the documentation, as noted in single comments.

2020-06-22 16:34 UTC, JohnHalleyGotway approved these changes
I approve of these changes.

2020-06-22 17:38 UTC, georgemccabe commented
Latest changes only involve documentation and previous test runs in Travis succeeded, so merging into develop even though travis has not completed.

2020-06-22 17:38 UTC, merged