Feature 502 create configurable bin dir
dtcenter/METplus pull request #505
Opened 2020-06-10 02:46 UTC by jprestop

Created for Issue #502.  Testing using Travis CI build: https://www.travis-ci.org/github/NCAR/METplus/branches

2020-06-10 13:52 UTC, georgemccabe requested changes
I would recommend allowing MET_BIN_DIR to be unset or set to an empty string so that the MET tools can be found from the path (i.e. using modules to obtain MET). This would involve adding a default value in the calls to self.config.getdir, i.e.

`self.config.getdir('MET_BIN_DIR', '')`

I would also mention in the documentation that you can set MET_BIN_DIR to an empty string if the MET tools are found in the user's path, i.e. when using module load.

Also, it is a bit nit-picky, but I would suggest you line up the arguments to os.path.join. For example, in ascii2nc_wrapper.py line 33:

```
self.app_path = os.path.join(config.getdir('MET_BIN_DIR', ''),
                             self.app_name)
```

(remove space before self.app_name so it lines up with config)

2020-06-10 18:14 UTC, jprestop commented
Thanks, George!  I made the requested changes. Please let me know if I need to do anything else.  I re-requested review.

2020-06-11 21:24 UTC, georgemccabe requested changes
A couple minor changes, but otherwise I approve!

2020-06-11 21:24 UTC, georgemccabe commented on docs/Contributors_Guide/create_wrapper.rst
> +        self.app_path = os.path.join(self.p.getdir('MET_BIN_DIR'), 'new_tool')
Add default value here.
```suggestion
        self.app_path = os.path.join(self.p.getdir('MET_BIN_DIR', ''),
                                     'new_tool')
```

2020-06-11 21:24 UTC, georgemccabe commented on parm/metplus_config/metplus_system.conf
> +## MET binary directory
```suggestion
## MET binary directory
# Set this to an empty string to find the MET tools from the path
```

2020-06-15 17:02 UTC, merged