Feature 607 dockermigrate
dtcenter/METplus pull request #622
Opened 2020-09-21 19:03 UTC by fentoad72

Moved all Docker files, DOCKERFILE, and docker_*.sh script into new director ci/docker

Changed paths in travis.yml and other shell scripts under ci/travis_jobs to point to ci/docker as needed

Using 3.1 tags for data because develop is incomplete

Are we moving toward one. big datafile instead of components for 4.0 and beyond/?

Link to data caching

2020-09-21 19:05 UTC, fentoad72 commented
Related to #597 
Relatead to Data Caching

2020-09-22 00:43 UTC, georgemccabe requested changes
I made a few comments inline.

We should check with @JohnHalleyGotway , but I'm not sure we want to remove the Dockerfile and build hooks for docker_data. The Dockerfile is needed to run docker build for the docker data volumes and the build hooks file I thought was going to be used to trigger the data volume creation and then create a big data volume that contains all of the subsets.

2020-09-22 00:43 UTC, georgemccabe commented on .travis.yml
>    - 3.7
I would remove 3.7 from the version list so we only run with 1 version of python, unless we really need multiple versions here. Most stages/jobs explicitly list the python version, so I don't know that having an extra version is doing much at this time.

2020-09-22 00:43 UTC, georgemccabe commented on ci/docker/docker_setup.sh
> +#${TRAVIS_BUILD_DIR}/ci/docker/get_data_volumes.py
I'm not entirely sure if these docker_* scripts belong in ci/docker. They are run by Travis. I think ci/docker should contain only things used exclusively by Docker, i.e. build hooks, Dockerfile, etc.

2020-09-22 00:43 UTC, georgemccabe commented on ci/docker/get_data_volumes.py
> +#METPLUS_VERSION = 'develop'
We need to be sure that we update this back to develop once those are all available or else new use cases will fail.

2020-09-22 18:45 UTC, georgemccabe commented
I just pushed a change to use 'develop' as the branch version for the data volumes used in tests and added support for an additional argument to get_data_volumes.py of 'all_metplus_data.' Once the Travis builds passed, I will merge into develop and check that Docker properly triggers the builds for metplus and metplus-data.

2020-09-22 22:46 UTC, merged