Feature 627 coherence spectra
dtcenter/METplus pull request #891
Opened 2021-04-22 22:17 UTC by fisherhucar

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, and **Milestone**
- [ ] After submitting the PR, select **Linked Issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2021-04-23 00:11 UTC, bikegeek commented on docs/use_cases/model_applications/s2s/SpaceTimeCrossSpectra.py
> +#        -c /path/to/METplus/parm/use_cases/model_applications/s2s/hovmoeller_diagram.conf \
Should this be hovmoeller conf file or the UserScript_obsPrecip_obsOnly_CrossSpectraPlot.conf?

2021-04-23 00:11 UTC, bikegeek commented on docs/use_cases/model_applications/s2s/SpaceTimeCrossSpectra.py
> +# 2) Modifying the configurations in parm/metplus_config, then passing in hovmoeller_diagram.conf::
same here, should this be hovmoeller?

2021-04-23 00:12 UTC, bikegeek commented on docs/use_cases/model_applications/s2s/UserScript_obsPrecip_obsOnly_CrossSpectraPlot.py
> +UserScript: Make a Hovmoeller plot
Hovmoeller or Cross spectra plot?

2021-04-23 00:12 UTC, bikegeek commented on docs/use_cases/model_applications/s2s/UserScript_obsPrecip_obsOnly_CrossSpectraPlot.py
> +# 1) Passing in hovmoeller_diagram.conf,
hovmoeller or cross spectra conf or UserScript_obsPrecip_obsOnly_CrossSpectraPlot.conf?

2021-04-23 00:17 UTC, bikegeek reviewed
Documentation has what appears to be cut-and-paste from hovmoeller plot.  Some instances of hovmoeller need to be replaced with cross spectra references instead.  Or am I mistaken?

2021-04-27 17:20 UTC, bikegeek approved these changes
No more mentions of hovmoeller in the docs.  I approve this request

2021-04-27 19:14 UTC, georgemccabe requested changes
We discussed in an email that the cartopy issues in GitHub Actions can be remedied by merging in the latest changes from develop.

Also, the new use case is not in the list of cases to run. This should be added to the following files:

* .github/workflows/main.yml
* internal_tests/use_cases/all_use_cases.txt

Also, make sure to assign a different number to this use case since the pull request for issue #626 (PR #889) is also open and is adding a new use case to the same category. You should be able to skip the number used in #889 and use the next one.

2021-04-27 19:17 UTC, georgemccabe commented on docs/use_cases/model_applications/s2s/SpaceTimeCrossSpectra.py
> +"""
It looks like this filename should also change to match the use case name.

2021-05-03 15:44 UTC, georgemccabe commented
The 2 failed tests on the pull request workflow are from the diff tests (new data doesn't exist in truth data set because it is new) for this use case and #626 (PR #889). This PR can be merged but develop-ref should be updated from develop to include the new test data.

2021-05-03 15:44 UTC, merged